// ===========================================
// SEED DATA - Protocolo 2 Hipertrofia
// 5 treinos do PDF do Wanderson
// ===========================================

const PROTOCOL_DATA = {
  name: "PROTOCOLO 2",
  goal: "Hipertrofia",
  level: "Intermediário",
  cardio: "Realizar cardio em todos os treinos de 20 a 40 minutos, na esteira com inclinação ou na bike",
  notes: [
    "Tirar fotos de comparações no início e final de ciclo",
    "Mantenha a postura em todos os movimentos sem perder a intensidade",
    "Movimentos sempre controlados",
    "Realize contrações excêntricas sempre com calma e respeitando a velocidade",
    "Se esforçar ao máximo que puder sempre e respeitar sinais de fadiga e lesão",
    "Treinar sempre no máximo da intensidade que o número de repetições pedir"
  ]
};

const WORKOUTS_SEED = [
  {
    letter: "A",
    name: "Treino A",
    sub: "Peito · Ombros · Tríceps",
    color: "#FF3D00",
    icon: "🔴",
    position: 0,
    exercises: [
      { is_mobility: true, name: "Alongamento de Dorsal", sets: 2, reps: "15 seg", rest: 30, duration_sec: 15, position: 0 },
      { is_mobility: true, name: "Alongamento de Peitoral no Espaldar", sets: 2, reps: "15 seg", rest: 30, duration_sec: 15, position: 1 },
      { name: "Supino Inclinado com Halteres", sets: 4, reps: "ver instruções", rest: 90, position: 2,
        instructions: "1 série de aquecimento de 10 a 12 rep\n1 série de 8 a 10 rep\n2 séries de 6 a 8 rep",
        muscles_primary: ["Peito"], muscles_secondary: ["Tríceps", "Ombros"] },
      { name: "Supino Reto com Halteres", sets: 3, reps: "6 a 8", rest: 90, position: 3,
        instructions: "3 séries de 6 a 8 rep",
        muscles_primary: ["Peito"], muscles_secondary: ["Tríceps"] },
      { name: "Crossover Polia Alta", sets: 4, reps: "ver instruções", rest: 90, method: "drop_set", position: 4,
        instructions: "2 séries de 10 a 12 rep\n1 série de 8 a 10 rep\n1 série de 6 a 8 rep + DROP (tirar 30% da carga e fazer até a falha)",
        muscles_primary: ["Peito"], muscles_secondary: ["Ombros"] },
      { name: "Elevação Lateral com Halteres", sets: 4, reps: "ver instruções", rest: 90, method: "cluster_set", position: 5,
        instructions: "2 séries de 8 a 10 rep\n1 série de 6 a 8 rep\n1 série de CLUSTER-SET: fazer 4 rep e dar intervalo de 20 seg, fazer mais 4 rep e dar intervalo de 20 seg, fazer mais 4 rep e fechou a série",
        muscles_primary: ["Ombros"] },
      { name: "Desenvolvimento Sentado com Halter", sets: 4, reps: "ver instruções", rest: 90, position: 6,
        instructions: "3 séries de 6 a 8 rep\n1 série com 20% menos carga até a falha",
        muscles_primary: ["Ombros"], muscles_secondary: ["Tríceps"] },
      { name: "Tríceps Testa com Halteres", sets: 4, reps: "ver instruções", rest: 90, position: 7,
        instructions: "2 séries de 10 a 12 rep\n2 séries de 8 a 10 rep\nUm halter em cada mão",
        muscles_primary: ["Tríceps"] }
    ]
  },
  {
    letter: "B",
    name: "Treino B",
    sub: "Costas · Bíceps · Lombar",
    color: "#FF8F00",
    icon: "🟠",
    position: 1,
    exercises: [
      { is_warmup: true, name: "W com Elástico", sets: 1, reps: "12 rep", rest: 30, position: 0 },
      { is_warmup: true, name: "Elevação Y com Halteres no Banco", sets: 2, reps: "12 rep", rest: 30, position: 1 },
      { is_mobility: true, name: "Alongamento de Dorsal", sets: 1, reps: "15 seg", rest: 30, duration_sec: 15, position: 2 },
      { name: "Pulldown Barra Reta", sets: 4, reps: "ver instruções", rest: 90, method: "backoff", position: 3,
        instructions: "1 série de 10 a 12 rep\n2 séries de 8 a 10 rep\n1 série de 6 a 8 rep + BACKOFF (dar intervalo de 30 seg, tirar 20% da carga e fazer até a falha)",
        muscles_primary: ["Costas"] },
      { name: "Puxada Pulley Barra Aberta Pegada Pronada", sets: 4, reps: "ver instruções", rest: 90, position: 4,
        instructions: "2 séries de 8 a 10 rep\n1 série de 6 a 8 rep\n1 série com 20% menos carga até a falha",
        muscles_primary: ["Costas"] },
      { name: "Remada Baixa Unilateral Neutra", sets: 4, reps: "ver instruções", rest: 90, position: 5,
        instructions: "2 séries de 8 a 10 rep\n1 série de 6 a 8 rep\n1 série de 6 a 8 rep + dar intervalo de 20 seg e fazer até a falha",
        muscles_primary: ["Costas"] },
      { name: "Pullface Corda na Polia", sets: 3, reps: "ver instruções", rest: 90, position: 6,
        instructions: "2 séries de 8 a 10 rep\n1 série de 6 a 8 rep",
        muscles_primary: ["Ombros"], muscles_secondary: ["Costas"] },
      { name: "Rosca Direta com Halteres", sets: 3, reps: "ver instruções", rest: 90, method: "three_seven", position: 7,
        instructions: "2 séries de 8 a 10 rep\n1 série de 3/7: faz 7 rep e 15 seg de intervalo, faz 6 rep e 15 seg de intervalo, faz 5 rep e 15 seg de intervalo, faz 4 rep e 15 seg de intervalo, faz 3 rep e fechou a série",
        muscles_primary: ["Bíceps"] },
      { name: "Rosca Direta Banco Inclinado", sets: 3, reps: "8 a 10", rest: 90, position: 8,
        instructions: "3 séries de 8 a 10 rep",
        muscles_primary: ["Bíceps"] },
      { name: "Hiperextensão de Lombar Solo", sets: 3, reps: "10 a 12", rest: 60, position: 9,
        instructions: "3 séries de 10 a 12 rep",
        muscles_primary: ["Lombar"], muscles_secondary: ["Glúteos"] }
    ]
  },
  {
    letter: "C",
    name: "Treino C",
    sub: "Posterior · Glúteo · Abdômen",
    color: "#FFD600",
    icon: "🟡",
    position: 2,
    exercises: [
      { is_mobility: true, name: "Alongamento Borboleta Deitado", sets: 1, reps: "15 seg", rest: 30, duration_sec: 15, position: 0 },
      { is_mobility: true, name: "Alongamento de Piriforme e Glúteo Médio", sets: 1, reps: "15 seg", rest: 30, duration_sec: 15, position: 1 },
      { is_mobility: true, name: "Alongamento de Iliopsoas e Reto Femoral", sets: 1, reps: "15 seg", rest: 30, duration_sec: 15, position: 2 },
      { is_warmup: true, name: "Mobilidade de Quadril de Cócoras", sets: 2, reps: "10 rep", rest: 30, position: 3 },
      { is_warmup: true, name: "Mobilidade de Tornozelo", sets: 2, reps: "10 rep", rest: 30, position: 4 },
      { name: "Abdominal Supra Banco Declinado", sets: 3, reps: "10 a 12", rest: 90, position: 5,
        instructions: "3 séries de 10 a 12 rep (segurar peso acima da linha da cabeça)",
        muscles_primary: ["Abdômen"] },
      { name: "Abdominal Oblíquo Alternado", sets: 3, reps: "10 a 12 cada", rest: 60, position: 6,
        instructions: "3 séries de 10 a 12 rep cada lado",
        muscles_primary: ["Abdômen"] },
      { name: "Cadeira Flexora", sets: 4, reps: "ver instruções", rest: 90, position: 7,
        instructions: "1 série de 10 a 12 rep\n2 séries de 8 a 10 rep\n1 série de 6 a 8 rep",
        muscles_primary: ["Isquiotibiais"] },
      { name: "Leg Press 45", sets: 4, reps: "ver instruções", rest: 90, method: "cluster_set", position: 8,
        instructions: "2 séries de 8 a 10 rep\n1 série de 6 a 8 rep\n1 série de CLUSTER-SET: fazer 4 rep e dar intervalo de 20 seg, fazer mais 4 rep e dar intervalo de 20 seg, fazer mais 4 rep e fechou a série",
        muscles_primary: ["Quadríceps", "Glúteos"], muscles_secondary: ["Isquiotibiais"] },
      { name: "Afundo no Smith", sets: 4, reps: "ver instruções", rest: 90, position: 9,
        instructions: "3 séries de 6 a 8 rep\n1 série com 20% menos carga até a falha\nDar intervalo de 20 seg entre as pernas",
        muscles_primary: ["Quadríceps", "Glúteos"] },
      { name: "Mesa Flexora", sets: 3, reps: "ver instruções", rest: 90, method: "drop_set", position: 10,
        instructions: "2 séries de 6 a 8 rep\n1 série de 6 a 8 rep + DROP (tirar 20% da carga e fazer até a falha)",
        muscles_primary: ["Isquiotibiais"] },
      { name: "Cadeira Abdutora 45 Graus", sets: 3, reps: "8 a 10", rest: 90, position: 11,
        instructions: "3 séries de 8 a 10 rep",
        muscles_primary: ["Glúteos"] },
      { name: "Panturrilha no Leg Press Horizontal", sets: 4, reps: "ver instruções", rest: 90, position: 12,
        instructions: "2 séries de 8 a 10 rep\n2 séries de 6 a 8 rep",
        muscles_primary: ["Panturrilha"] }
    ]
  },
  {
    letter: "D",
    name: "Treino D",
    sub: "Ombros · Peito · Costas (Upper)",
    color: "#E040FB",
    icon: "🟣",
    position: 3,
    exercises: [
      { is_warmup: true, name: "Mobilidade de Ombro I", sets: 2, reps: "8 a 10", rest: 30, position: 0,
        instructions: "2 séries de 8 a 10 rep" },
      { is_warmup: true, name: "Mobilidade Torácica X", sets: 2, reps: "8 a 10", rest: 30, position: 1,
        instructions: "2 séries de 8 a 10 rep" },
      { name: "Elevação Lateral com Halteres", sets: 4, reps: "ver instruções", rest: 90, method: "cluster_set", position: 2,
        instructions: "2 séries de 8 a 10 rep\n1 série de 6 a 8 rep\n1 série de CLUSTER-SET (4/4/4): faz 4 rep e dá intervalo de 15 seg, faz 4 rep e dá intervalo de 15 seg, faz 4 rep e fechou a série",
        muscles_primary: ["Ombros"] },
      { name: "Desenvolvimento Sentado com Halter", sets: 4, reps: "ver instruções", rest: 90, position: 3,
        instructions: "2 séries de 8 a 10 rep\n2 séries de 6 a 8 rep",
        muscles_primary: ["Ombros"], muscles_secondary: ["Tríceps"] },
      { name: "Supino Máquina (Pegada Pronada)", sets: 4, reps: "ver instruções", rest: 90, method: "cluster_set", position: 4,
        instructions: "2 séries de 8 a 10 rep\n1 série de 6 a 8 rep\n1 série de CLUSTER-SET (4/4/4): faz 4 rep e dá intervalo de 15 seg, faz 4 rep e dá intervalo de 15 seg, faz 4 rep e fechou a série",
        muscles_primary: ["Peito"], muscles_secondary: ["Tríceps", "Ombros"] },
      { name: "Pullover com Halteres", sets: 4, reps: "ver instruções", rest: 90, position: 5,
        instructions: "2 séries de 10 a 12 rep\n2 séries de 8 a 10 rep",
        muscles_primary: ["Costas"], muscles_secondary: ["Peito"] },
      { name: "Puxada Pulley Barra Aberta Pegada Supinada", sets: 4, reps: "ver instruções", rest: 90, method: "backoff", position: 6,
        instructions: "2 séries de 8 a 10 rep\n1 série de 6 a 8 rep\n1 série de 6 a 8 rep + BACKOFF (tirar 30% da carga, dar intervalo de 20 seg e fazer até a falha)",
        muscles_primary: ["Costas"], muscles_secondary: ["Bíceps"] },
      { name: "Remada T", sets: 3, reps: "ver instruções", rest: 90, method: "backoff", position: 7,
        instructions: "2 séries de 8 a 10 rep\n1 série de 6 a 8 rep + BACKOFF (tirar 30% da carga, dar intervalo de 20 seg e fazer até a falha)",
        muscles_primary: ["Costas"] },
      { name: "Tríceps Testa na Polia com Corda + Rosca Martelo na Polia (BISET)", sets: 3, reps: "ver instruções", rest: 90, method: "biset", position: 8,
        instructions: "BISET (combinar os 2 exercícios):\nTríceps Testa: 3 séries de 8 a 10 rep\nRosca Martelo: 3 séries de 10 a 12 rep",
        muscles_primary: ["Tríceps", "Bíceps"] }
    ]
  },
  {
    letter: "E",
    name: "Treino E",
    sub: "Quadríceps · Posterior · Panturrilha",
    color: "#00BCD4",
    icon: "🔵",
    position: 4,
    exercises: [
      { is_mobility: true, name: "Alongamento de Piriforme e Glúteo Médio", sets: 1, reps: "15 seg", rest: 30, duration_sec: 15, position: 0 },
      { is_mobility: true, name: "Alongamento Borboleta Deitado", sets: 1, reps: "15 seg", rest: 30, duration_sec: 15, position: 1 },
      { is_mobility: true, name: "Alongamento de Iliopsoas e Reto Femoral", sets: 1, reps: "15 seg", rest: 30, duration_sec: 15, position: 2 },
      { is_warmup: true, name: "Mobilidade de Quadril de Cócoras", sets: 2, reps: "10 rep", rest: 30, position: 3 },
      { is_warmup: true, name: "Mobilidade de Tornozelo", sets: 2, reps: "10 rep", rest: 30, position: 4 },
      { name: "Agachamento Smith", sets: 4, reps: "ver instruções", rest: 90, position: 5,
        instructions: "1 série de 10 a 12 rep\n2 séries de 8 a 10 rep\n1 série de 6 a 8 rep",
        muscles_primary: ["Quadríceps", "Glúteos"] },
      { name: "Leg Press Horizontal Unilateral", sets: 3, reps: "6 a 8", rest: 90, position: 6,
        instructions: "3 séries de 6 a 8 rep",
        muscles_primary: ["Quadríceps", "Glúteos"] },
      { name: "Cadeira Extensora", sets: 4, reps: "ver instruções", rest: 90, method: "drop_set", position: 7,
        instructions: "2 séries de 8 a 10 rep\n1 série de 6 a 8 rep\n1 série de 6 a 8 rep + DROP (tirar 30% da carga e fazer até a falha)",
        muscles_primary: ["Quadríceps"] },
      { name: "Stiff com Barra", sets: 3, reps: "8 a 10", rest: 90, position: 8,
        instructions: "3 séries de 8 a 10 rep",
        muscles_primary: ["Isquiotibiais", "Glúteos"] },
      { name: "Gêmeos Sentado", sets: 4, reps: "ver instruções", rest: 90, position: 9,
        instructions: "2 séries de 8 a 10 rep\n2 séries de 6 a 8 rep",
        muscles_primary: ["Panturrilha"] },
      { name: "Panturrilha no Smith com Step", sets: 3, reps: "ver instruções", rest: 90, method: "drop_set", position: 10,
        instructions: "2 séries de 10 a 12 rep\n1 série de 8 a 10 rep + DROP (tirar 20% da carga e fazer até a falha)",
        muscles_primary: ["Panturrilha"] }
    ]
  }
];
